-- ═══════════════════════════════════════════════════════════════════════
-- NEXUP AI WORKFORCE — PHASE 3 (Command idempotency ledger)
-- ═══════════════════════════════════════════════════════════════════════
--
-- STATUS: PROPOSED — NOT APPLIED TO ANY DATABASE.
--
-- Apply order: AI_WORKFORCE_PHASE_1A, then AI_WORKFORCE_PHASE_1B, then
-- AI_WORKFORCE_PHASE_2, then this file.
--
-- Generated by `prisma migrate diff`, not written by hand:
--
--   git show HEAD:prisma/schema.prisma > .tmp-schema-old.prisma
--   npx prisma migrate diff --from-schema=.tmp-schema-old.prisma \
--                           --to-schema=prisma/schema.prisma --script
--
-- Rules honoured, and checked mechanically by
-- `node scripts/verify-proposed-migration.mjs <this file>`:
--
--   * ADDITIVE ONLY: one CREATE TABLE and its four indexes.
--   * No DROP, no DELETE, no TRUNCATE, no RENAME, and no ALTER TABLE at all —
--     the legacy schema, and the four Phase-2 lifecycle tables, stay
--     byte-identical afterwards.
--   * No foreign key into a legacy table, and deliberately none into
--     `ai_missions` either: the ledger must be able to record a claim BEFORE a
--     mission exists (that ordering is what makes the claim atomic), so
--     `missionId` is a plain indexed reference like every other cross-table id
--     in this schema.
--   * `state` is TEXT validated by the application state machine
--     (`command-intent-contracts.ts`), not a Postgres enum.
--   * Nothing here is registered in `prisma/migrations/`, so
--     `prisma migrate deploy` cannot pick it up by accident.
--
-- Why the table exists at all: the mission lifecycle had no Command identity.
-- Two retries of the same human/agent request would create two Missions, two
-- task sets and — with a real runtime — two real provider turns. The unique
-- index on ("scope", "idempotencyKey") is the whole algorithm: the claim is ONE
-- insert, so two concurrent callers cannot both win, and the loser reads the
-- winner's mission instead of creating a second one.
-- ═══════════════════════════════════════════════════════════════════════

-- CreateTable
CREATE TABLE "ai_command_intents" (
    "id" TEXT NOT NULL,
    "scope" TEXT NOT NULL,
    "idempotencyKey" TEXT NOT NULL,
    "commandHash" TEXT NOT NULL,
    "state" TEXT NOT NULL DEFAULT 'CLAIMED',
    "missionId" TEXT,
    "requestedBy" TEXT NOT NULL,
    "capabilityId" TEXT,
    "reason" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ai_command_intents_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "ai_command_intents_missionId_idx" ON "ai_command_intents"("missionId");

-- CreateIndex
CREATE INDEX "ai_command_intents_state_idx" ON "ai_command_intents"("state");

-- CreateIndex
CREATE INDEX "ai_command_intents_createdAt_idx" ON "ai_command_intents"("createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "ai_command_intents_scope_idempotencyKey_key" ON "ai_command_intents"("scope", "idempotencyKey");
