-- ═══════════════════════════════════════════════════════════════════════
-- NEXUP AI WORKFORCE — PHASE 2 (the Step-5 mission lifecycle)
-- ═══════════════════════════════════════════════════════════════════════
--
-- STATUS: PROPOSED — NOT APPLIED TO ANY DATABASE.
--
-- Apply order: AI_WORKFORCE_PHASE_1A, then AI_WORKFORCE_PHASE_1B, then this.
--
-- Generated by `prisma migrate diff`, not written by hand:
--
--   git show HEAD:prisma/schema.prisma > .tmp-schema-old.prisma
--   npx prisma migrate diff --from-schema=.tmp-schema-old.prisma \
--                           --to-schema=prisma/schema.prisma --script
--
-- Rules honoured, and checked mechanically by
-- `node scripts/verify-proposed-migration.mjs <this file>`:
--
--   * ADDITIVE ONLY: four CREATE TABLE, their indexes, and six FOREIGN KEY
--     constraints that reference only those four tables.
--   * No DROP, no DELETE, no TRUNCATE, no RENAME, and no ALTER TABLE against a
--     table that already exists — the legacy schema is byte-identical
--     afterwards.
--   * No foreign key into a legacy table (users, businesses, clients, projects):
--     actor, business, workspace, project and client ids stay plain indexed
--     columns, exactly as the Phase-1 tables did, so the legacy models need no
--     back-relation fields.
--   * Lifecycle STATE is TEXT, validated by the TypeScript state machines
--     (`mission-contracts.ts`, `task-contracts.ts`, `task-review.ts`). A state
--     is a code change, not an `ALTER TYPE` that cannot run in a transaction.
--   * Nothing here is registered in `prisma/migrations/`, so
--     `prisma migrate deploy` cannot pick it up by accident.
--
-- The four tables carry the Step-5 lifecycle end to end:
--
--   ai_missions ──1:N── ai_tasks ──1:N── ai_execution_records
--                                └──1:N── ai_task_reviews
--
-- ═══════════════════════════════════════════════════════════════════════

-- CreateTable
CREATE TABLE "ai_missions" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "goal" TEXT NOT NULL,
    "businessId" TEXT,
    "workspaceRef" TEXT,
    "projectRef" TEXT,
    "clientRef" TEXT,
    "createdBy" TEXT NOT NULL,
    "owner" TEXT,
    "participants" JSONB NOT NULL DEFAULT '[]',
    "state" TEXT NOT NULL,
    "priority" TEXT NOT NULL DEFAULT 'NORMAL',
    "contextRefs" JSONB NOT NULL DEFAULT '[]',
    "jobRefs" JSONB NOT NULL DEFAULT '[]',
    "taskRefs" JSONB NOT NULL DEFAULT '[]',
    "approvals" JSONB NOT NULL DEFAULT '[]',
    "outputs" JSONB NOT NULL DEFAULT '[]',
    "history" JSONB NOT NULL DEFAULT '[]',
    "createdAt" TIMESTAMP(3) NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "startedAt" TIMESTAMP(3),
    "finishedAt" TIMESTAMP(3),

    CONSTRAINT "ai_missions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ai_tasks" (
    "id" TEXT NOT NULL,
    "missionId" TEXT NOT NULL,
    "sequence" INTEGER NOT NULL,
    "title" TEXT NOT NULL,
    "objective" TEXT NOT NULL,
    "input" JSONB NOT NULL DEFAULT '{}',
    "assignedActorId" TEXT,
    "requiredCapabilityId" TEXT,
    "requiredCapabilityVersion" TEXT,
    "dependsOn" JSONB NOT NULL DEFAULT '[]',
    "state" TEXT NOT NULL,
    "attempt" INTEGER NOT NULL DEFAULT 0,
    "maxAttempts" INTEGER NOT NULL DEFAULT 2,
    "executionRecordId" TEXT,
    "executionHandleId" TEXT,
    "reviewId" TEXT,
    "result" JSONB,
    "error" JSONB,
    "history" JSONB NOT NULL DEFAULT '[]',
    "createdAt" TIMESTAMP(3) NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "startedAt" TIMESTAMP(3),
    "finishedAt" TIMESTAMP(3),

    CONSTRAINT "ai_tasks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ai_execution_records" (
    "id" TEXT NOT NULL,
    "handleId" TEXT NOT NULL,
    "runtimeId" TEXT NOT NULL,
    "actorId" TEXT NOT NULL,
    "capabilityId" TEXT NOT NULL,
    "capabilityVersion" TEXT,
    "assignmentId" TEXT,
    "missionId" TEXT,
    "taskId" TEXT,
    "attempt" INTEGER NOT NULL DEFAULT 1,
    "providerExecutionId" TEXT,
    "status" TEXT NOT NULL,
    "idempotencyKey" TEXT,
    "replayed" BOOLEAN NOT NULL DEFAULT false,
    "startedAt" TIMESTAMP(3) NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "completedAt" TIMESTAMP(3),
    "durationMs" INTEGER,
    "output" JSONB,
    "outputText" TEXT,
    "error" JSONB,
    "cancelledAt" TIMESTAMP(3),
    "cancelledReason" TEXT,
    "audit" JSONB NOT NULL DEFAULT '[]',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ai_execution_records_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ai_task_reviews" (
    "id" TEXT NOT NULL,
    "taskId" TEXT NOT NULL,
    "missionId" TEXT NOT NULL,
    "executionRecordId" TEXT NOT NULL,
    "state" TEXT NOT NULL DEFAULT 'PENDING',
    "summary" TEXT NOT NULL,
    "reviewerActorId" TEXT,
    "requestedBy" TEXT NOT NULL,
    "requestedAt" TIMESTAMP(3) NOT NULL,
    "decidedBy" TEXT,
    "decidedAt" TIMESTAMP(3),
    "note" TEXT,

    CONSTRAINT "ai_task_reviews_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "ai_missions_state_idx" ON "ai_missions"("state");

-- CreateIndex
CREATE INDEX "ai_missions_businessId_idx" ON "ai_missions"("businessId");

-- CreateIndex
CREATE INDEX "ai_missions_projectRef_idx" ON "ai_missions"("projectRef");

-- CreateIndex
CREATE INDEX "ai_missions_clientRef_idx" ON "ai_missions"("clientRef");

-- CreateIndex
CREATE INDEX "ai_missions_createdAt_idx" ON "ai_missions"("createdAt");

-- CreateIndex
CREATE INDEX "ai_tasks_missionId_idx" ON "ai_tasks"("missionId");

-- CreateIndex
CREATE INDEX "ai_tasks_state_idx" ON "ai_tasks"("state");

-- CreateIndex
CREATE INDEX "ai_tasks_assignedActorId_idx" ON "ai_tasks"("assignedActorId");

-- CreateIndex
CREATE INDEX "ai_tasks_requiredCapabilityId_idx" ON "ai_tasks"("requiredCapabilityId");

-- CreateIndex
CREATE UNIQUE INDEX "ai_tasks_missionId_sequence_key" ON "ai_tasks"("missionId", "sequence");

-- CreateIndex
CREATE INDEX "ai_execution_records_handleId_idx" ON "ai_execution_records"("handleId");

-- CreateIndex
CREATE INDEX "ai_execution_records_providerExecutionId_idx" ON "ai_execution_records"("providerExecutionId");

-- CreateIndex
CREATE INDEX "ai_execution_records_idempotencyKey_idx" ON "ai_execution_records"("idempotencyKey");

-- CreateIndex
CREATE INDEX "ai_execution_records_status_idx" ON "ai_execution_records"("status");

-- CreateIndex
CREATE INDEX "ai_execution_records_runtimeId_idx" ON "ai_execution_records"("runtimeId");

-- CreateIndex
CREATE INDEX "ai_execution_records_actorId_idx" ON "ai_execution_records"("actorId");

-- CreateIndex
CREATE INDEX "ai_execution_records_missionId_idx" ON "ai_execution_records"("missionId");

-- CreateIndex
CREATE INDEX "ai_execution_records_taskId_idx" ON "ai_execution_records"("taskId");

-- CreateIndex
CREATE INDEX "ai_execution_records_updatedAt_idx" ON "ai_execution_records"("updatedAt");

-- CreateIndex
CREATE UNIQUE INDEX "ai_execution_records_taskId_attempt_key" ON "ai_execution_records"("taskId", "attempt");

-- CreateIndex
CREATE INDEX "ai_task_reviews_taskId_idx" ON "ai_task_reviews"("taskId");

-- CreateIndex
CREATE INDEX "ai_task_reviews_missionId_idx" ON "ai_task_reviews"("missionId");

-- CreateIndex
CREATE INDEX "ai_task_reviews_state_idx" ON "ai_task_reviews"("state");

-- CreateIndex
CREATE INDEX "ai_task_reviews_requestedAt_idx" ON "ai_task_reviews"("requestedAt");

-- CreateIndex
CREATE INDEX "ai_task_reviews_reviewerActorId_idx" ON "ai_task_reviews"("reviewerActorId");

-- AddForeignKey
ALTER TABLE "ai_tasks" ADD CONSTRAINT "ai_tasks_missionId_fkey" FOREIGN KEY ("missionId") REFERENCES "ai_missions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ai_execution_records" ADD CONSTRAINT "ai_execution_records_missionId_fkey" FOREIGN KEY ("missionId") REFERENCES "ai_missions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ai_execution_records" ADD CONSTRAINT "ai_execution_records_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "ai_tasks"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ai_task_reviews" ADD CONSTRAINT "ai_task_reviews_taskId_fkey" FOREIGN KEY ("taskId") REFERENCES "ai_tasks"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ai_task_reviews" ADD CONSTRAINT "ai_task_reviews_missionId_fkey" FOREIGN KEY ("missionId") REFERENCES "ai_missions"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ai_task_reviews" ADD CONSTRAINT "ai_task_reviews_executionRecordId_fkey" FOREIGN KEY ("executionRecordId") REFERENCES "ai_execution_records"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

