-- ═══════════════════════════════════════════════════════════════════════
-- NEXUP AI WORKFORCE — PHASE 4 (durable execution-claim ledger)
-- ═══════════════════════════════════════════════════════════════════════
--
-- STATUS: PROPOSED — NOT APPLIED TO ANY DATABASE.
--
-- Apply order: AI_WORKFORCE_PHASE_1A, then AI_WORKFORCE_PHASE_1B, then
-- AI_WORKFORCE_PHASE_2, then AI_WORKFORCE_PHASE_3, then this file. This file
-- has no dependency of its own beyond a database that can hold a table: it
-- references no other table, so applying it alone is also valid.
--
-- Generated by `prisma migrate diff`, not written by hand:
--
--   git show HEAD:prisma/schema.prisma > .tmp-schema-old.prisma
--   npx prisma migrate diff --from-schema=.tmp-schema-old.prisma \
--                           --to-schema=prisma/schema.prisma --script
--
-- Rules honoured, and checked mechanically by
-- `node scripts/verify-proposed-migration.mjs <this file>`:
--
--   * ADDITIVE ONLY: one CREATE TABLE and its five indexes (2 unique, 3 plain).
--   * TWO uniqueness mechanisms guard ONE attempt: UNIQUE("idempotencyKey") makes
--     a retry of the same key resolve to the same row, and
--     UNIQUE("taskId", "attempt") makes `taskId + attempt` — the semantic
--     identity of an execution attempt — impossible to duplicate even if a future
--     caller spells the idempotency key differently. Correctness must not rest on
--     every caller deriving the identical string. A conflict on EITHER is
--     absorbed by the adapter into a typed outcome; neither may surface as a raw
--     uniqueness error. The composite unique index also serves `listForTask` (it
--     is a `taskId` prefix index), which is why there is no separate `taskId`
--     index.
--   * No DROP, no DELETE, no TRUNCATE, no RENAME, and no ALTER TABLE at all —
--     the legacy schema and every earlier ai_* table stay byte-identical.
--   * No foreign key at all. A claim is a DELIVERY/LEASE ledger, not part of
--     the mission lifecycle, so `missionId` / `taskId` are plain indexed
--     references exactly like `ai_command_intents` (and for the same reason the
--     Phase-3 ledger states: an id may be recorded before the row it names, and
--     a lease must never be able to block a task's own lifecycle writes).
--   * `state` is TEXT validated by the application state machine
--     (`execution-claim.ts`), not a Postgres enum, so a new state is a code
--     change rather than an ALTER TYPE.
--   * Nothing here is registered in `prisma/migrations/`, so
--     `prisma migrate deploy` cannot pick it up by accident.
--
-- Why the table exists at all: before Step 5A a mission task was dispatched by
-- calling the runtime FIRST and writing the execution record second, with no
-- durable record of who owned the attempt. Two concurrent advances both
-- dispatched; a crash between the call and the write left a real provider run
-- nobody could adopt. The UNIQUE index on `idempotencyKey` is the whole
-- algorithm: claiming an attempt is ONE insert, so two callers cannot both win,
-- and the loser reads what the winner did instead of starting a second run.
--
-- The states this table can hold, and the recovery rule for each:
--   CLAIMED      dispatch was never ATTEMPTED    → safe to reclaim once lapsed
--   DISPATCHING  dispatch was ENTERED            → NEVER reclaimed; a run MAY exist
--   DISPATCHED   an execution is durably known   → adopt, never duplicate
--   RELEASED     refused before dispatch         → no run exists; free again
--   UNVERIFIED   entered, no handle: park for a human — never re-dispatchable
--
-- `leaseExpiresAt` is written and compared with `now() AT TIME ZONE 'UTC'` by
-- the adapter, so lease expiry is decided by the DATABASE clock and a skewed
-- application instance cannot expire a healthy peer's claim.
-- ═══════════════════════════════════════════════════════════════════════

-- CreateTable
CREATE TABLE "ai_execution_claims" (
    "id" TEXT NOT NULL,
    "missionId" TEXT NOT NULL,
    "taskId" TEXT NOT NULL,
    "attempt" INTEGER NOT NULL,
    "actorId" TEXT NOT NULL,
    "capabilityId" TEXT NOT NULL,
    "runtimeId" TEXT,
    "idempotencyKey" TEXT NOT NULL,
    "state" TEXT NOT NULL DEFAULT 'CLAIMED',
    "executionRecordId" TEXT,
    "handleId" TEXT,
    "leaseOwner" TEXT,
    "leaseExpiresAt" TIMESTAMP(3),
    "detail" TEXT,
    "claimedAt" TIMESTAMP(3) NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ai_execution_claims_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "ai_execution_claims_idempotencyKey_key" ON "ai_execution_claims"("idempotencyKey");

-- CreateIndex
CREATE INDEX "ai_execution_claims_missionId_idx" ON "ai_execution_claims"("missionId");

-- CreateIndex
CREATE INDEX "ai_execution_claims_state_idx" ON "ai_execution_claims"("state");

-- CreateIndex
CREATE INDEX "ai_execution_claims_leaseExpiresAt_idx" ON "ai_execution_claims"("leaseExpiresAt");

-- CreateIndex
CREATE UNIQUE INDEX "ai_execution_claims_taskId_attempt_key" ON "ai_execution_claims"("taskId", "attempt");
